# Generated by Django 4.2.3 on 2023-07-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category_color',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
