# Generated by Django 4.2.3 on 2023-07-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_category_alter_task_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
